- name: Remove Oracle Home
  file:
    path: "{{ oracle_home }}"
    state: absent
  
- name: Remove Oracle Inventory
  file:
    path: "{{ oracle_inventory }}"
    state: absent
  
- name: Remove oraInst.loc
  file:
    path: /etc/oraInst.loc
    state: absent
  
- name: Remove oratab
  file:
    path: /etc/oratab
    state: absent