- import_tasks: passwordfile.yaml

- import_tasks: initora.yaml

- import_tasks: tnsnames.yaml

- import_tasks: startup.yaml

- import_tasks: duplicate.yaml

- import_tasks: recovery.yaml

- import_tasks: validate.yaml

- import_tasks: create_spfile.yaml
