- name: Stop database
  become: yes
  become_user: oracle
  shell: |
    export ORACLE_HOME={{ oracle_home }}
    export ORACLE_SID={{ oracle_sid }}
    export PATH=$ORACLE_HOME/bin:$PATH

    sqlplus / as sysdba <<EOF
    shutdown immediate;
    exit;
    EOF
  ignore_errors: yes

- name: Remove database with DBCA
  become: yes
  become_user: oracle
  shell: |
    export ORACLE_HOME={{ oracle_home }}
    export ORACLE_SID={{ oracle_sid }}
    export PATH=$ORACLE_HOME/bin:$PATH

    dbca -silent -deleteDatabase \
      -sourceDB {{ oracle_sid }} \
      -sysDBAUserName sys \
      -sysDBAPassword "{{ sys_password }}"
  register: dbca_delete
  failed_when:
    - dbca_delete.rc != 0
    - "'Database deletion completed.' not in dbca_delete.stdout"
  

- name: Remove Oracle datafiles
  become: yes
  file:
    path: "{{ oracle_datafile_destination }}/{{ oracle_sid | upper }}"
    state: absent

- name: Remove fast recovery area
  become: yes
  file:
    path: "{{ oracle_recovery_file_dest }}/{{ oracle_sid }}"
    state: absent
  ignore_errors: yes

- name: Remove password file
  become: yes
  file:
    path: "{{ oracle_home }}/dbs/orapw{{ oracle_sid }}"
    state: absent
  ignore_errors: yes

- name: Remove spfile
  become: yes
  file:
    path: "{{ oracle_home }}/dbs/spfile{{ oracle_sid }}.ora"
    state: absent
  ignore_errors: yes

- name: Remove init file
  become: yes
  file:
    path: "{{ oracle_home }}/dbs/init{{ oracle_sid }}.ora"
    state: absent
  ignore_errors: yes