- name: "START Infrastructure"
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - role: ec2_oracle_control
      operation: start
      tags: ec2

- name: "START Oracle"
  hosts: oracle_servers
  become: true
  become_user: oracle
  gather_facts: false

  roles:
    - role: ec2_oracle_control
      operation: start
      tags: oracle