- name: "AWS | Build instance list"
  set_fact:
    instance_ids: >-
      {{
        [
          hostvars[groups['bastion'][0]]['ec2_instance_id'] | default(None),
          hostvars[groups['primary'][0]]['ec2_instance_id'] | default(None),
          hostvars[groups['standby'][0]]['ec2_instance_id'] | default(None)
        ]
        | select('ne', None)
        | list
      }}

- name: "AWS | Stop instances"
  amazon.aws.ec2_instance:
    instance_ids: "{{ instance_ids }}"
    state: stopped
    region: "{{ aws_region }}"
    wait: true