- name: Oracle STOP
  include_tasks: oracle_stop.yaml
  when:
    - operation == "stop"
    - inventory_hostname != "localhost"

- name: EC2 STOP
  include_tasks: ec2_stop.yaml
  when:
    - operation == "stop"
    - inventory_hostname == "localhost"

- name: EC2 START
  include_tasks: ec2_start.yaml
  when:
    - operation == "start"
    - inventory_hostname == "localhost"

- name: Oracle START
  include_tasks: oracle_start.yaml
  when:
    - operation == "start"
    - inventory_hostname != "localhost"