- name: "ORACLE | Stop MRP on STANDBY"
  shell: |
    sqlplus -s / as sysdba <<EOF
    ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;
    EXIT;
    EOF
  register: mrp_stop
  failed_when: false
  changed_when: false
  when: "'standby' in group_names"

- name: "ORACLE | Shutdown database"
  shell: |
    sqlplus -s / as sysdba <<EOF
    SHUTDOWN IMMEDIATE;
    EXIT;
    EOF
  register: oracle_shutdown
  failed_when: false
  changed_when: false

- name: "ORACLE | Stop listener"
  shell: lsnrctl stop
  register: listener_stop
  failed_when: false
  changed_when: false